### PR TITLE
Several changes for added robustness (and more)

### PR DESCRIPTION
**Pull request by ronaldkunenborg**
- can now have warnings in list for later processing, especially for the cases fixed in this release
- can handle incorrect filesize in metadata
- aligns read with block_align size
- can handle misaligned chunks
- can handle misaligned LIST form type ID due to null-terminated "LIST" tag
- no longer crashes in prepare_read when trying to raise an error because path is undefined
- added reporting of warnings to example.py

### CODE REVIEW

**Comment by ronaldkunenborg** [comment]
Hi, I've added a pull request (duh, obvious) but if you feel it's a bit much in one go, I can also roll it back and put in separate fixes for each issue. Still working on testfiles though - I can't just copy the testfiles I have due to copyright reasons and I do want testfiles. I can probably generate the files if I just copy chunks from other wave files and have some sinus wave as sound data. Still working on that one :)

**Comment by Zuzu-Typ** [comment]
> Hi, I've added a pull request (duh, obvious) but if you feel it's a bit much in one go, I can also roll it back and put in separate fixes for each issue. 

Awesome, thanks ^^
And no, don't worry, it's okay this way, I just gotta take a quick looksy first (;

**Comment by Zuzu-Typ** [comment]
I've added a few docstrings and moved the standalone functions into the Wave class.

**Comment by ronaldkunenborg** [comment]
I've integrated your changes. Looks good! I've added more metadata to the example.py (not sure if that is actually a good idea, as that also means changing the docs) and added a pytest test file.

**Comment by ronaldkunenborg** [comment]
Hi, quick question: are you going to integrate the pull request fairly quickly, or later on? I have a number of additional items that I'd like to do once this is integrated in the master, but if you're also doing them I'll go work on something else in the mean time to avoid double work. 

I will, in the mean time, add documentation about pytest to the main docs, as well as a pytest_requirements.txt file for use with "pip install -r pytest_requirements.txt" in this branch. Hope to finish that up today.

**Comment by Zuzu-Typ** [comment]
> Hi, quick question: are you going to integrate the pull request fairly quickly, or later on?

I should be able to integrate it relatively quickly.
I just want to wait until you're done with everything you want to have in this PR.
Then I can take a look myself and merge it (:

**Comment by ronaldkunenborg** [comment]
> > Hi, quick question: are you going to integrate the pull request fairly quickly, or later on?
> 
> I should be able to integrate it relatively quickly.
> I just want to wait until you're done with everything you want to have in this PR.
> Then I can take a look myself and merge it (:

Ah okay. But there's more than just robustness. It's also metadata extensions, more chunks, etc. - but I'll add all of them then. Just be warned :)

**Comment by ronaldkunenborg** [comment]
For the moment I'm done. The only thing I still had on my list was support for the FACT chunk. I will eventually do that once everything is stable and merged into the master.

**Pull request merged**
